version: '3.8'

services:
  # 1. VERİTABANI
  db:
    image: postgres:15-alpine
    container_name: nexus_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nexus_drive
      - POSTGRES_USER=nexus_user
      - POSTGRES_PASSWORD=nexus_pass
    ports:
      - "5432:5432"
    networks:
      - nexus_network

  # 2. DEPOLAMA (MinIO - S3)
  minio:
    image: minio/minio
    container_name: nexus_minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # API Portu
      - "9001:9001" # Yönetim Paneli
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    networks:
      - nexus_network

  # 3. BACKEND
  backend:
    build: ./backend  
    container_name: nexus_backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - minio
      - meilisearch
    environment:
      - DB_HOST=db
      - DB_NAME=nexus_drive
      - DB_USER=nexus_user
      - DB_PASSWORD=nexus_pass
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_USE_SSL=False
    networks:
      - nexus_network

  # 4. FRONTEND
  frontend:
    build: ./frontend 
    container_name: nexus_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - backend
    networks:
      - nexus_network

  # --- PROMETHEUS (Veri Toplayıcı) ---
  prometheus:
    image: prom/prometheus:latest
    container_name: nexus_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - nexus_network

  # --- GRAFANA (Görsel Panel) ---
  grafana:
    image: grafana/grafana:latest
    container_name: nexus_grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - nexus_network

  # --- MEILISEARCH (Araç) ---
  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: nexus_meilisearch
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=nexus_master_key
    volumes:
      - meili_data:/meili_data
    networks:       
      - nexus_network


# Verilerin kaybolmaması için Docker Volume'leri
volumes:
  postgres_data:
  minio_data:
  meili_data:

# Konteynerlerin birbiriyle konuşması için özel ağ
networks:
  nexus_network:
    driver: bridge