global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nexus_backend'
    metrics_path: '/prometheus/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['nexus_backend:8000', 'backend:8000']