apiVersion: v1
kind: Secret
metadata:
  name: nexus-secrets
type: Opaque
stringData:
  POSTGRES_DB: "nexus_drive"
  POSTGRES_USER: "nexus_user"
  POSTGRES_PASSWORD: "nexus_password123"
  MINIO_ROOT_USER: "minioadmin"
  MINIO_ROOT_PASSWORD: "minioadmin"
  MEILI_MASTER_KEY: "nexus_master_key"